input {
# Данные поступят по GELF (Docker gelf logging driver)
  gelf {
    port => 12201
  }
}
filter {
# Воспользуемся фильтром grok и разобьём строку на несколько полей
    grok {
        # Grok структурирует логи при помощи grok-шаблонов, выглядящих как %{PATTERN:ID}
        # Под капотом каждого паттерна находится регулярное выражение. Это позволяет logstash понять, какие данные он должен найти в сообщении
        # А ID задаёт название этому участку строки
        # Список стандартных паттернов можно найти на github https://github.com/logstash-plugins/logstash-patterns-core/blob/main/patterns/ecs-v1/grok-patterns
        # Быстро протестировать корректность вашего паттерна можно в онлайн-отладчике https://grokdebugger.com/

        match => { "message" => "%{DATA:log_timestamp} - %{DATA:logger_name} - %{LOGLEVEL:level} - %{GREEDYDATA:log_message}" }
        tag_on_failure => ["_grokparsefailure"]
    }
}
output {
    elasticsearch {
        hosts => ["${ELASTICSEARCH_LOGS_URL}"]
        index => "%{tag}-%{+YYYY.MM.dd}"
    }
}
