# Generated by Django 4.2.11 on 2026-08-11 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('delivery_channels', models.JSONField(default=list, help_text='Список каналов доставки: ["email", "sms", "push"]', verbose_name='delivery channels')),
                ('recipient_type', models.CharField(choices=[('all', 'All users'), ('by_subscription', 'By subscription level'), ('manual', 'Manual selection')], default='all', max_length=20, verbose_name='recipient type')),
                ('subscription_level', models.IntegerField(blank=True, default=0, help_text='Минимальный уровень подписки для получателей', null=True, verbose_name='subscription level')),
                ('send_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('recurring', 'Recurring')], default='immediate', max_length=20, verbose_name='send type')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Дата и время отправки (для отложенных и повторяющихся)', null=True, verbose_name='scheduled at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'content"."notification',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(help_text='Тема сообщения. Поддерживает переменные: {{user_name}}, {{movie_title}}, etc.', max_length=500, verbose_name='subject')),
                ('content', models.TextField(help_text='Содержимое сообщения. Поддерживает переменные: {{user_name}}, {{movie_title}}, etc.', verbose_name='content')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
                'db_table': 'content"."notification_template',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('interval_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly', max_length=20, verbose_name='interval type')),
                ('day_of_week', models.IntegerField(blank=True, help_text='День недели (0-6, где 0=понедельник). Для weekly.', null=True, verbose_name='day of week')),
                ('day_of_month', models.IntegerField(blank=True, help_text='День месяца (1-31). Для monthly.', null=True, verbose_name='day of month')),
                ('month', models.IntegerField(blank=True, help_text='Месяц (1-12). Для yearly.', null=True, verbose_name='month')),
                ('end_date', models.DateField(blank=True, help_text='Дата окончания повторений', null=True, verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedule', to='notifications.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'recurring schedule',
                'verbose_name_plural': 'recurring schedules',
                'db_table': 'content"."recurring_schedule',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True, verbose_name='user ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('channel', models.CharField(max_length=20, verbose_name='channel')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'notification log',
                'verbose_name_plural': 'notification logs',
                'db_table': 'content"."notification_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate', verbose_name='template'),
        ),
    ]
