# Generated by Django 4.2.11 on 2026-08-15 15:01

import uuid

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='NotificationTemplate',
                    fields=[
                        ('id', models.UUIDField(_('id'), primary_key=True, default=uuid.uuid4, editable=False)),
                        ('name', models.CharField(_('name'), max_length=255)),
                        ('code', models.CharField(_('code'), max_length=255, unique=True)),
                        ('channel', models.CharField(_('channel'), max_length=20, choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')])),
                        ('subject', models.CharField(_('subject'), max_length=500, blank=True, null=True)),
                        ('body', models.TextField(_('body'))),
                        ('allowed_variables', models.JSONField(_('allowed variables'), default=list)),
                        ('is_active', models.BooleanField(_('is active'), default=True)),
                        ('created', models.DateTimeField(_('created'), auto_now_add=True)),
                        ('modified', models.DateTimeField(_('modified'), blank=True, null=True)),
                    ],
                    options={
                        'verbose_name': 'notification template',
                        'verbose_name_plural': 'notification templates',
                        'db_table': 'content"."notification_template',
                        'ordering': ['-created'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE content.notification_template (
                        id uuid NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
                        name varchar(255) NOT NULL,
                        code varchar(255) NOT NULL UNIQUE,
                        channel varchar(20) NOT NULL,
                        subject varchar(500),
                        body text NOT NULL,
                        allowed_variables jsonb NOT NULL,
                        is_active boolean NOT NULL,
                        created timestamptz NOT NULL,
                        modified timestamptz NULL
                    );
                    CREATE INDEX notification_template_code_like ON content.notification_template (code varchar_pattern_ops);
                    """,
                    reverse_sql="""
                    DROP TABLE IF EXISTS content.notification_template;
                    """,
                ),
            ],
        ),
    ]